language: node_js

cache: yarn

git:
    quiet: true

node_js:
    - '10'
    - '12'
    - '14'

# os
dist: focal

os:
    - linux
    - osx
    - windows

osx_image: xcode12

# See https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
    - YARN_GPG=no

# safelist
branches:
    only:
        - master
        - /^feat/.*$/
        - /^v\d*\.\d*\.\d*$/
        - /^dependabot/.*$/

script:
    - echo "Running tests against $(node -v)..."
    - cp .env.template .env.test
    - yarn test

jobs:
    include:
        - stage: test
          name: produce coverage
          node_js: lts/*
          os: linux
          script:
              - cp .env.template .env.test
              - jest --coverage
              - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
              - rm -rf ./coverage
        - name: check for code duplication
          node_js: lts/*
          os: linux
          script: yarn dupe-check
